name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SECRET_NAME }}
          password: ${{ secrets.SECRET_PASS }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.SECRET_NAME }}/trabalhovaldinei:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.SECRET_NAME }}/trabalhovaldinei:latest